package crypto

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/sha256"
	"fmt"
	"io"

	cryptotypes "github.com/horizen-pes/pkg/common/crypto"
	"golang.org/x/crypto/hkdf"
)

const (
	// AES-256
	aesKeySize = 32
)

/*
Encrypt encrypts a generic byte array.
Sender and receiver keys must use Elliptic Curve Diffie-Hellman over NIST curve (25519 is not suitable).
A shared derived AES key is generated with the aboves, and the message is encrypted with AES-256-GCM.
A random nonce is used for the encryption and prepended to the generated bytes.
*/
func Encrypt(senderPrivKey *cryptotypes.PrivateKeyP521, receiverPubKey *cryptotypes.PublicKeyP521, message []byte) ([]byte, error) {
	sharedKey, err := senderPrivKey.ECDH(receiverPubKey.PublicKey)
	if err != nil {
		return nil, fmt.Errorf("failed to compute shared key: %w", err)
	}
	sharedAESKey, err := deriveAES256Key(sharedKey)
	if err != nil {
		return nil, fmt.Errorf("failed to derive AES key: %w", err)
	}

	return EncryptWithAES(sharedAESKey, message)
}

// EncryptWithAES encrypts a generic byte array with a given AES-256 key.
func EncryptWithAES(key cryptotypes.AES256Key, message []byte) ([]byte, error) {
	block, err := aes.NewCipher(key[:])
	if err != nil {
		return nil, fmt.Errorf("failed to create new cipher: %w", err)
	}
	aesgcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("failed to create new GCM: %w", err)
	}
	// generate IV (nonce) for AES-256-GCM
	nonce := make([]byte, aesgcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return nil, fmt.Errorf("failed to generate nonce: %w", err)
	}

	ciphertext := aesgcm.Seal(nil, nonce, message, nil)

	// Prepend nonce at the ciphertext
	return append(nonce, ciphertext...), nil
}

/*
Decrypt decrypts a chipertext.
Sender and receiver keys must use Elliptic Curve Diffie-Hellman over NIST curve (25519 is not suitable).
The input array must contain the nonce prepended.
*/
func Decrypt(senderPubKey *cryptotypes.PublicKeyP521, receiverPrivKey *cryptotypes.PrivateKeyP521, message []byte) ([]byte, error) {
	sharedKey, err := receiverPrivKey.ECDH(senderPubKey.PublicKey)
	if err != nil {
		return nil, fmt.Errorf("failed to compute shared key: %w", err)
	}
	sharedAESKey, err := deriveAES256Key(sharedKey)
	if err != nil {
		return nil, fmt.Errorf("failed to derive AES key: %w", err)
	}
	return DecryptWithAES(sharedAESKey, message)
}

// DecryptWithAES decrypts a chipertext with a given AES-256 key.
func DecryptWithAES(key cryptotypes.AES256Key, message []byte) ([]byte, error) {
	block, err := aes.NewCipher(key[:])
	if err != nil {
		return nil, fmt.Errorf("failed to create new cipher: %w", err)
	}
	aesgcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("failed to create new GCM: %w", err)
	}
	nonceSize := aesgcm.NonceSize()
	if len(message) < nonceSize {
		return nil, fmt.Errorf("ciphertext too short")
	}
	nonce, ciphertext := message[:nonceSize], message[nonceSize:]

	plainMessage, err := aesgcm.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to decrypt message: %w", err)
	}
	return plainMessage, nil
}

func deriveAES256Key(secret []byte) (cryptotypes.AES256Key, error) {
	h := hkdf.New(sha256.New, secret, nil, nil)
	key := make([]byte, aesKeySize)
	if _, err := io.ReadFull(h, key); err != nil {
		return cryptotypes.AES256Key{}, fmt.Errorf("failed to derive key: %w", err)
	}
	return cryptotypes.AES256Key(key), nil
}
