package crypto

import (
	"crypto/aes"
	"crypto/cipher"
	ecdh "crypto/ecdh"
	"crypto/rand"
	"crypto/sha256"
	"io"
	"log"

	"golang.org/x/crypto/hkdf"
)

/*
Generate a private key with Elliptic Curve Diffie-Hellman over NIST P-521 curve, also known as secp521r1.
(This can be used for encryption/decription)
*/
func GeneratePrivateKeyP521() *ecdh.PrivateKey {
	curve := ecdh.P521()
	newKey, _ := curve.GenerateKey(rand.Reader)
	return newKey
}

/*
Generate a private key with Elliptic Curve 25519
(This is the curve used in Ethereum)
*/
func GeneratePrivateKey25519() *ecdh.PrivateKey {
	curve := ecdh.X25519()
	newKey, _ := curve.GenerateKey(rand.Reader)
	return newKey
}

/*
Encrypts a generic byte array.
Sender and receiver keys must use Elliptic Curve Diffie-Hellman over NIST curve (25519 is not suitable).
A shared derived AES key is generated with the aboves, and the message is encrypted with AES-256-GCM.
A random nonce is used for the encryption and prepended to the generated bytes.
*/
func Encrypt(senderPrivKey *ecdh.PrivateKey, receiverPubKey *ecdh.PublicKey, message []byte) []byte {
	sharedKey, _ := senderPrivKey.ECDH(receiverPubKey)
	sharedAESKey := deriveAES256Key(sharedKey)

	// generate IV (nonce) for AES-256-GCM
	nonce := make([]byte, 12)
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		panic(err)
	}
	block, _ := aes.NewCipher(sharedAESKey)
	aesgcm, _ := cipher.NewGCM(block)
	ciphertext := aesgcm.Seal(nil, nonce, message, nil)

	// Prepend nonce at the ciphertext
	return append(nonce, ciphertext...)
}

/*
Decrypts a chipertext.
Sender and receiver keys must use Elliptic Curve Diffie-Hellman over NIST curve (25519 is not suitable).
The input array must contain the nonce prepended.
*/
func Decrypt(senderPubKey *ecdh.PublicKey, receiverPrivKey *ecdh.PrivateKey, message []byte) []byte {
	sharedKey, _ := receiverPrivKey.ECDH(senderPubKey)
	sharedAESKey := deriveAES256Key(sharedKey)
	block, _ := aes.NewCipher(sharedAESKey)
	aesgcm, _ := cipher.NewGCM(block)
	nonce := message[:12]
	ciphertext := message[12:]
	plainMessage, _ := aesgcm.Open(nil, nonce, ciphertext, nil)
	return plainMessage
}

func deriveAES256Key(secret []byte) []byte {
	h := hkdf.New(sha256.New, secret, nil, nil)
	key := make([]byte, 32)
	if _, err := io.ReadFull(h, key); err != nil {
		log.Fatal(err)
	}
	return key
}
