package crypto

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/ecdh"
	"crypto/rand"
	"crypto/sha256"
	"fmt"
	"io"

	"golang.org/x/crypto/hkdf"
)

const (
	// AES-256
	aesKeySize = 32
)

/*
GeneratePrivateKeyP521 generates a private key with Elliptic Curve Diffie-Hellman over NIST P-521 curve,
also known as secp521r1.
(This can be used for encryption/decription)
*/
func GeneratePrivateKeyP521() (*ecdh.PrivateKey, error) {
	curve := ecdh.P521()
	newKey, err := curve.GenerateKey(rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("failed to generate private key: %w", err)
	}
	return newKey, nil
}

/*
GeneratePrivateKey25519 generates a private key with Elliptic Curve 25519.
(This is the curve used in Ethereum)
*/
func GeneratePrivateKey25519() (*ecdh.PrivateKey, error) {
	curve := ecdh.X25519()
	newKey, err := curve.GenerateKey(rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("failed to generate private key: %w", err)
	}
	return newKey, nil
}

/*
Encrypt encrypts a generic byte array.
Sender and receiver keys must use Elliptic Curve Diffie-Hellman over NIST curve (25519 is not suitable).
A shared derived AES key is generated with the aboves, and the message is encrypted with AES-256-GCM.
A random nonce is used for the encryption and prepended to the generated bytes.
*/
func Encrypt(senderPrivKey *ecdh.PrivateKey, receiverPubKey *ecdh.PublicKey, message []byte) ([]byte, error) {
	sharedKey, err := senderPrivKey.ECDH(receiverPubKey)
	if err != nil {
		return nil, fmt.Errorf("failed to compute shared key: %w", err)
	}
	sharedAESKey, err := deriveAES256Key(sharedKey)
	if err != nil {
		return nil, fmt.Errorf("failed to derive AES key: %w", err)
	}

	block, err := aes.NewCipher(sharedAESKey)
	if err != nil {
		return nil, fmt.Errorf("failed to create new cipher: %w", err)
	}
	aesgcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("failed to create new GCM: %w", err)
	}
	// generate IV (nonce) for AES-256-GCM
	nonce := make([]byte, aesgcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return nil, fmt.Errorf("failed to generate nonce: %w", err)
	}

	ciphertext := aesgcm.Seal(nil, nonce, message, nil)

	// Prepend nonce at the ciphertext
	return append(nonce, ciphertext...), nil
}

/*
Decrypt decrypts a chipertext.
Sender and receiver keys must use Elliptic Curve Diffie-Hellman over NIST curve (25519 is not suitable).
The input array must contain the nonce prepended.
*/
func Decrypt(senderPubKey *ecdh.PublicKey, receiverPrivKey *ecdh.PrivateKey, message []byte) ([]byte, error) {
	sharedKey, err := receiverPrivKey.ECDH(senderPubKey)
	if err != nil {
		return nil, fmt.Errorf("failed to compute shared key: %w", err)
	}
	sharedAESKey, err := deriveAES256Key(sharedKey)
	if err != nil {
		return nil, fmt.Errorf("failed to derive AES key: %w", err)
	}
	block, err := aes.NewCipher(sharedAESKey)
	if err != nil {
		return nil, fmt.Errorf("failed to create new cipher: %w", err)
	}
	aesgcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("failed to create new GCM: %w", err)
	}
	nonceSize := aesgcm.NonceSize()
	if len(message) < nonceSize {
		return nil, fmt.Errorf("ciphertext too short")
	}
	nonce, ciphertext := message[:nonceSize], message[nonceSize:]

	plainMessage, err := aesgcm.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to decrypt message: %w", err)
	}
	return plainMessage, nil
}

func deriveAES256Key(secret []byte) ([]byte, error) {
	h := hkdf.New(sha256.New, secret, nil, nil)
	key := make([]byte, aesKeySize)
	if _, err := io.ReadFull(h, key); err != nil {
		return nil, fmt.Errorf("failed to derive key: %w", err)
	}
	return key, nil
}
