#CHANNEL_TYPE=tcp
#EXECUTOR_PORT=4000
#EXECUTOR_LOG_NETWORK_LEVEL=info
#LOG_SERVER_IP_HOST=127.0.0.1
#EXECUTOR_IP_HOST=127.0.0.1

CHANNEL_TYPE=vsock
EXECUTOR_PORT=4000
EXECUTOR_ADMIN_PORT=4001
EXECUTOR_KMS_ENABLED=true
EXECUTOR_KMS_KEY_ARN=arn:aws:kms:eu-west-1:215705706013:key/7be0593e-72e9-46f2-9a9f-9a85a0e719e4
EXECUTOR_KMS_REGION=eu-west-1
EXECUTOR_KMS_PROXY_PORT=8000
