CHANNEL_TYPE=tcp
EXECUTOR_IP_ADDRESS=localhost
EXECUTOR_PORT=8080
EXECUTOR_LOG_CONSOLE=true
EXECUTOR_LOG_CONSOLE_LEVEL=info
EXECUTOR_LOG_CONSOLE_COLOR=true
EXECUTOR_LOG_FILE_NAME=executor.log
EXECUTOR_LOG_FILE_LEVEL=debug
