CHANNEL_TYPE=tcp

# Admin command server settings
MANAGER_ADMIN_PORT=4002
MANAGER_IP_HOST=localhost

CHAIN_PROCESSOR_ADDRESS=0x0000000000000000000000000000000000000000
MANAGER_DATA_FOLDER=/tmp/horizen-pes-data/manager_db
LOG_SERVER_FILE_NAME=/tmp/log_server.log
MANAGER_REPORTS_FOLDER=/tmp/horizen-pes-data/manager_reports
