name: Horizen CCE CI
on:
  push:
    branches: [ main, dev, pc/dockerpub ]
    tags:
      - 'v*'       # triggers job on any tag starting with 'v'
  pull_request:
    branches: [ main, dev ]

env:
  DOCKER_HUB_ORG: ${{ vars.DOCKER_HUB_ORG }}
  DOCKER_HUB_USERNAME: ${{ vars.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  GITHUB_TAG: ${{ github.ref_name }}

jobs:
  build-and-push-docker-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Build and push executor image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/executor/Dockerfile
          push: false
          tags: |
            ${{ env.DOCKER_HUB_ORG }}/cce-executor:${{ env.GITHUB_TAG }}
            ${{ env.DOCKER_HUB_ORG }}/cce-executor:latest
